# 1.Promise的含义
promise,是一个保存着,未来才会结束,的事件的结果,的对象。

两个特点：
- 对象的状态不受外界的影响。
- 一旦状态改变,就不会再变,任何时候都可以得到这个结果。

缺点：
- 无法取消Promise,一旦创建,立即执行,无法中途取消。
- 如果不设置回调,Promise内部抛出的错误,不会反映到外部。
- 当处于pending状态时,无法得知当前进展到哪个阶段（刚刚开始,还是即将完成）。

# 2.基础用法
```javascript
const promise = new Promise((resolve,reject)=> {
  /*逻辑代码*/
  setTimeout(resolve,1000,'rose')
})

promise.then((name)=> {
  console.log(name)
})
```

# 3.注意点
* [ ] 在一个Promise内部,返回另一个Promise时,第一个Promise的内部状态将失效,第二个Promise将影响第一个Promise的内部状态。
```javascript
const p1 = new Promise((resolve, reject) => {
  setTimeout(()=> reject(new Error('fail')),1000)
})

const p2 = new Promise((resolve, reject) => {
  setTimeout(()=> resolve(p1),1000)
})

p2.then( result => {
  console.log(result)
}).catch( err => {
  console.log(err)
})
```
p2内部返回的是另一个Promise,导致p2自己的状态失效了,由p1的状态决定p2的状态。后面的then指向的在上述代码中指向了p1。
* [ ] **内部代码的执行顺序**。（**同步代码**、**resolve**()等在事件循环中执行的顺序）。
```javascript
const promise = new Promise((resolve,reject) => {
  resolve(1)
  console.log('2')
})
promise.then(r => {
	console.log(r)
})
```
上述代码中,调用了resolve(1)之后,后面的console.log('2')还是会执行,并且先执行。这是因为立即resolve的Promise是在本轮事件循环的末尾执行,总是晚于本轮循环的同步事件。
# 4.Promise.prototype.then

# 5.Promise.prototype.catch
看几个例子
```javascript
const promise = new Promise((resolve, reject)=> {
	resolve('ok')
	throw new Error('test')
})
promise.then(value => console.log(value))
.catch(err => console.log(err))
```
catch方法不会被执行

# 6.Promise.all()
Promise.all()的用于将多个Promise实例,包装成一个新的Promise实例。
```javascript
const p = Promise.all([p1, p2, p3])
```
**Promise.all**方法接受一个数组作为参数,p1、p2、p3都是Promise实例,如果不是,则会在内部调用**Promise.resolve**()方法,将参数转为Promise实例,再进一步处理。
```javascript
const p1 = new Promise((resolve, reject) => {
  resolve('123')
}).then(value=> {
  return 123444
})

const p2 = new Promise((resolve, reject) => {
  reject(new Error('error'))
})

Promise.all([p1,p2]).then(data=> console.log(data))
.catch(err=>console.log(err))
```
如果作为参数的Promise实例,定义了自己的catch方法,那么它一旦被rejected,并不会触发Promise.all()的catch方法。
# 7.Promise.race()
用法和Promise.all()类似。
```javascript
const p = Promise.race([fetch(url,opts), 
  new Promise((resolve,reject) => {
    setTimeout(()=> {reject(new Error('超时'))}, 100)
})])
```
上述代码定义了一个超时函数。
# 8.Promise.resolve()
该方法的主要作用在于将现有对象转化为Promise对象，并且该对象的状态为resolved。
```javascript
Promise.resolve('rose')
// 等价于
new Promise((resolve, reject) => {
	resolve('rose')
})
```
**Promise.resolve**方法的参数分为四种情况。
1. 参数是promise实例，则不做任何修改返回这个实例。
2. 参数是一个**thenable**对象，thenable对象指的是具有then方法的对象，Promise.resolve会将这个对象转化为Promise对象，然后立即执行thenable对象的then方法。
```javascript
let thenable = {
  then: (resolve,reject) => {
    resolve('rose')
  }
}
let p1 = Promise.resolve(thenable)
p1.then(value => {
  console.log(value)
})
```
3. 参数不是具有then方法的对象，或者压根就不是对象
```javascript
const p = Promise.resolve('rose')

p.then( value => {
	console.log(value)
})
```
返回的promise对象直接就是resolved，所以回调函数会立即执行。
4. 不带任何参数
直接返回一个resolved状态的promise对象。
# 9.Promise.reject()
Promise.reject()的作用和Promise.resolve()的作用类似。区别在于，Promise.reject()的参数，会原封不动作为reject的理由，变成后续方法的参数。
```javascript
const thenable = {
	then: (resolve, reject) => {
		reject('出错了')
	}
}

Promise.reject(thenable)
.catch(e => {
	console.log(e ===  thenable) // true, 这里的e是thenable对象
})
```
